"""Initial migration

Revision ID: 3da071866fac
Revises: 
Create Date: 2025-05-19 15:44:31.034810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da071866fac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom_utilisateur', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_utilisateurs_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_utilisateurs_nom_utilisateur'), ['nom_utilisateur'], unique=True)

    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('entreprise', sa.String(length=120), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('utilisateur_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journal_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journal_date'))

    op.drop_table('journal')
    op.drop_table('clients')
    with op.batch_alter_table('utilisateurs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_utilisateurs_nom_utilisateur'))
        batch_op.drop_index(batch_op.f('ix_utilisateurs_email'))

    op.drop_table('utilisateurs')
    # ### end Alembic commands ###
